---
- name: 配置keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
  - restart keepalived

- name: nginx主配置
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
  - reload nginx
 
- name: 配置nginx转发
  template: 
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: 邮件脚本配置
  template:
    src: send_mail.sh.j2
    dest: /etc/keepalived/send_mail.sh
    mode: 755
#  ingore_erros: yes

- name: 邮件服务SMTP配置
  template:
    src: mail.rc.j2
    dest: /etc/mail.rc

- name: nginx存活检查配置
  template:
    src: nginx_check.sh.j2
    dest: /etc/keepalived/nginx_check.sh
    mode: 755 

- name: 启动sendmail服务
  systemd:
    name: sendmail
    state: started
    enabled: yes

- name: 启动nginx服务
  systemd:
    name: nginx
    state: started
    enabled: yes
    
- name: 启动keepalived服务
  systemd:
    name: keepalived
    state: started
    enabled: yes


  
    
