---
# tasks file for redis

- name: 判断redis是否已经安装
  stat: 
    path: "{{ REDIS_HOME }}/bin/redis-server"
  register: redis_bin_file

- name: 判断主从是否部署
  shell:
    cmd: "grep '{{ redis_master_host }}' {{ REDIS_HOME }}/redis-{{ REDIS_PORT }}.conf"
  register: grep_result
  ignore_errors: True


- name: 查看变量
  debug:
    msg: "{{ redis_bin_file }}"

- name: 下载安装包
  unarchive:
    src: redis-5.0.13.tar.gz
    dest: /usr/local/src
  when: not redis_bin_file.stat.exists

- name: 安装编译环境
  yum:
    name: [cmake, gcc]
    state: installed
  when: 
  - not redis_bin_file.stat.exists

- name: 编译安装redis
  shell:
    chdir:  /usr/local/src/redis-5.0.13/
    cmd: "make && make PREFIX={{ REDIS_HOME }} install"
  when: not redis_bin_file.stat.exists

- name: 配置启动脚本
  template:
    src: redis.j2
    dest: "/usr/lib/systemd/system/redis-{{ REDIS_PORT }}.service"
    mode: 755
  when: not redis_bin_file.stat.exists

- name: 配置文件修改
  template:
    src: redis.conf.j2
    dest: "{{ REDIS_HOME }}/redis-{{ REDIS_PORT }}.conf"
  notify:
    restart redis-server
   
  
