---
- name: 查看sentinel_status变量状态
  debug:
    msg: "{{ sentinel_status }}"
  when: sentinel_status is defined

- name: 创建sentinel数据目录
  file:
    path: "{{ SENTINEL_DATA }}"
    state: directory
  when: 
  - sentinel_status is defined
  - sentinel_status == "install"  

- name: 配置sentinel
  template:
    src: sentinel.conf.j2
    dest: "{{ SENTINEL_DATA }}/sentinel-{{ SENTINEL_PORT }}.conf"
  when:
  - sentinel_status is defined
  - sentinel_status == "install"
  notify:
    restart sentinel-server

- name: 注册sentinel服务
  template:
    src: sentinel.service.j2
    dest: "/usr/lib/systemd/system/sentinel-{{ SENTINEL_PORT }}.service"
  when:
  - sentinel_status is defined
  - sentinel_status == "install"

